name: Rust-wasm-deploy


on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Use Node.js 22.x
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
    - name: Build
      run:
        cd wasm &&
        mkdir dist &&
        npm ci && npm run build &&
        cp -r ../scripts ./dist/scripts &&
        cp -r ./scripts/* ./dist/scripts/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wasm/dist
        force_orphan: true
